name: Godot CI/CD Pipeline

on: [push, pull_request]

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: ${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}
  PROJECT_PATH: .

jobs:
  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          echo $REPO_NAME
          mkdir -v -p build/web
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Web" "$EXPORT_DIR/web/index.html"
          zip -r HTML5.zip $EXPORT_DIR/web 
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HTML5
          path: $PROJECT_PATH/HTML5.zip

  deploy-to-itchio-web:
    runs-on: ubuntu-latest
    needs: export-web
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: HTML5
      - name: Deploy to Itch.io (HTML5)
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: web
          ITCH_GAME: ${{ secrets.ITCHIO_GAME }}
          ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
          PACKAGE: HTML5.zip
